### ISSUE TITLE
Links in wiki page not working

### ISSUE THREAD

**Issue by jeremyboggs** [pelagios/pelagios-cookbook#1]
The links to the XML and N-Triples examples under the **Example: Google Ancient Places** section on [Adding Dataset Metadata with VoID](https://github.com/pelagios/pelagios-cookbook/wiki/Adding-Dataset-Metadata-with-VoID) are redirecting to a form to add a new wiki page. I'm guessing the path to them should be changed to the full path to the example files.

**Comment by rsimon** [comment]
Ouch... thanks for letting us know ;-) Fixed!
