### ISSUE TITLE
Dead links in the Wiki

### ISSUE THREAD

**Issue by dersmon** [pelagios/pelagios-cookbook#2]
Hey!

The first two links [here](https://github.com/pelagios/pelagios-cookbook/wiki/List-of-Dataset-Summary-Examples) are dead.

Cheers,
Simon

**Comment by rsimon** [comment]
Many thanks for letting us know - fixed!

Cheers,
Rainer

**Comment by almereyda** [comment]
The API linked me to *Using the Pelagios API*, which also doesn't exist.

**Comment by rsimon** [comment]
Hi @almereyda,

can you point me to where you found that broken link? It's not at the page referenced in this thread. And on the front page of the Wiki, the link seems ok?

**Comment by almereyda** [comment]
Thanks for asking, found it again in https://github.com/pelagios/pelagios-api-v2/commit/51133d9ee6b0ad1539de58ef43327d7f9faab867#diff-0730bb7c2e8f9ea2438b52e419dd86c9R9

**Comment by rsimon** [comment]
Ah sorry - that page was about our old API which is already deprecated. Obviously, we should have properly shut down that page and link to the new version. I've done that now:

https://github.com/pelagios/pelagios-api-v2

For info about our current API, see

https://github.com/pelagios/peripleo

Thanks for pointing it out!
