### ISSUE TITLE
Problem with link to dainst.org

### ISSUE THREAD

**Issue by koenedaele** [pelagios/pelagios-cookbook#4]
On https://github.com/pelagios/pelagios-cookbook/wiki/Joining-Pelagios#the-dataset-summary there's a link to https://gazetteer.dainst.org/ that generates a warning about an insecure connection. Simple solution would be to change the link to http://gazetteer.dainst.org. More correct solution would probably be to get dainst.org to update their SSL configuration.

**Comment by rsimon** [comment]
thx for letting us know! changed the URL to http.
